name: Crear archivo en EC2

on:
  push:
    branches:
      - back
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso para configurar la clave privada
      - name: Configurar la clave privada
        run: |
          echo "$EC2_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      # Paso para conectarse a EC2 y crear el archivo
      - name: Conectarse a EC2 y crear prueba.txt
        env:
          EC2_HOST: "44.220.1.21"
          EC2_USER: "admin"
        run: |
          ssh -i private_key.pem $EC2_USER@$EC2_HOST "echo 'Este es un archivo de prueba' > ~/prueba.txt"
